# Generated by Django 5.2.1 on 2025-05-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_autor_livro'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='autor',
            field=models.ManyToManyField(blank=True, null=True, related_name='livros', to='core.autor'),
        ),
    ]
